=== Balti1991/stockprocessor/stockprocessor/stockprocessor-xml/src/main/xsd/processor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 sp1 (http://www.altova.com) by Kocsis Antal (Netvisor Kft.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://stockprocessor/handler/xml" targetNamespace="http://stockprocessor/handler/xml" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="processor">
		<xs:annotation>
			<xs:documentation>processor object</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:sequence maxOccurs="unbounded">
					<xs:element name="input">
						<xs:annotation>
							<xs:documentation>The input of xml processor and the the input sides of inner processors wired to it.</xs:documentation>
						</xs:annotation>
						<xs:complexType>
							<xs:attribute name="name" type="xs:string" use="required"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:sequence maxOccurs="unbounded">
					<xs:element name="output">
						<xs:annotation>
							<xs:documentation>The output of xml processor and the the output sides of inner processors wired to it.</xs:documentation>
						</xs:annotation>
						<xs:complexType>
							<xs:attribute name="name" type="xs:string" use="required"/>
							<xs:attribute name="type" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="StockAction"/>
										<xs:enumeration value="StockCandle"/>
										<xs:enumeration value="StockNumber"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:sequence>
					<xs:element name="usedProcessors">
						<xs:complexType>
							<xs:sequence minOccurs="0" maxOccurs="unbounded">
								<xs:choice>
									<xs:element name="extrnalProcessor">
										<xs:complexType>
											<xs:sequence minOccurs="0" maxOccurs="unbounded">
												<xs:element name="parameter">
													<xs:complexType>
														<xs:attribute name="name"/>
														<xs:attribute name="value"/>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
											<xs:attribute name="name" type="xs:string" use="required"/>
											<xs:attribute name="library" type="xs:string"/>
											<xs:attribute name="type" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
									<xs:element ref="ns1:processor"/>
								</xs:choice>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:sequence maxOccurs="unbounded">
					<xs:element name="innerWire">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="source" type="ns1:WireType">
									<xs:annotation>
										<xs:documentation>The source processor or an input from xml processor.</xs:documentation>
									</xs:annotation>
								</xs:element>
								<xs:element name="receiver" type="ns1:WireType">
									<xs:annotation>
										<xs:documentation>The receiver processor or an output from xml processor.</xs:documentation>
									</xs:annotation>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="description" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="WireType">
		<xs:attribute name="processorName" type="xs:string">
			<xs:annotation>
				<xs:documentation>The name of the target processor, if it is not the currently created.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="taget" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The processors target iconnectors name.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="ParameterType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="LIST"/>
			<xs:enumeration value="RANGE"/>
			<xs:enumeration value="ENUM"/>
			<xs:enumeration value="LOGICAL"/>
			<xs:enumeration value="STOCK_ACTION"/>
			<xs:enumeration value="STOCK_DATA"/>
			<xs:enumeration value="STOCK_DATA_NUMBER"/>
			<xs:enumeration value="STOCK_DATA_CANDLE"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Balti1991/stockprocessor/stockprocessor/stockprocessor-xml/src/main/xsd/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2008 sp1 (http://www.altova.com)-->
<ns1:processor name="Sample XML processor" xsi:schemaLocation="http://stockprocessor/handler/xml processor.xsd" xmlns:ns1="http://stockprocessor/handler/xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<!-- Input side -->
	<ns1:input name="Input">
		<ns1:wire processorName="Minimal processor" taget="Input"/>
	</ns1:input>
<!-- Output side -->
	<ns1:output name="Output 1" type="Candle data">
		<!--><ns1:wire processorName="Minimal processor" taget="Output"/>-->
	</ns1:output>
	<ns1:output name="Output 2" type="Number data">
		<ns1:wire processorName="nd1" taget="NumberData"/>
	</ns1:output>
<!-- Processors definitions -->
	<ns1:usedProcessors>
		<ns1:extrnalProcessor  name="nd1" library="Base Processors" type="Number data"/>
		<ns1:extrnalProcessor  name="nd2" library="Base Processors" type="Number data"/>
		<ns1:processor name="Minimal processor">
			<ns1:input name="Input"/>
			<ns1:output name="Output" type="Candle data"/>
			<ns1:usedProcessors/>
			<ns1:innerWire>
				<ns1:source taget="Input"/>
				<ns1:receiver taget="Output"/>
			</ns1:innerWire>
		</ns1:processor>
		<ns1:processor name="Minimal processor2">
			<ns1:input name="Input"/>
			<ns1:output name="Output" type="Candle data"/>
			<ns1:usedProcessors/>
			<ns1:innerWire>
				<ns1:source taget="Input"/>
				<ns1:receiver taget="Output"/>
			</ns1:innerWire>
		</ns1:processor>
	</ns1:usedProcessors>
<!-- Wires -->
	<ns1:innerWire>
		<ns1:source processorName="Minimal processor" taget="Output"/>
		<ns1:receiver processorName="nd1" taget="Input"/>
	</ns1:innerWire>
</ns1:processor>
